USE [master]
GO

/****** Object:  Database [CoinApi]    Script Date: 9-3-2018 16:48:38 ******/
CREATE DATABASE [CoinApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoinApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CoinApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoinApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CoinApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CoinApi] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoinApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoinApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoinApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoinApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoinApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoinApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoinApi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoinApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoinApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoinApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoinApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoinApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoinApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoinApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoinApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoinApi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoinApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoinApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoinApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoinApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoinApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoinApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoinApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoinApi] SET RECOVERY FULL 
GO

ALTER DATABASE [CoinApi] SET  MULTI_USER 
GO

ALTER DATABASE [CoinApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoinApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoinApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoinApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoinApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoinApi] SET QUERY_STORE = OFF
GO

USE [CoinApi]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CoinApi] SET  READ_WRITE 
GO

