//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pair
    {
        public string asset_id_base { get; set; }
        public string asset_id_quote { get; set; }
        public Nullable<int> count { get; set; }
        public int id { get; set; }
    }
}
